# Generated by Django 5.0.4 on 2024-05-13 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TravelerHub', max_length=30)),
                ('owner', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('state', models.CharField(default='Kerala', max_length=50)),
                ('country', models.CharField(default='india', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('1', 'Diamond'), ('2', 'Gold'), ('3', 'Silver')], max_length=50)),
                ('capacity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'available'), ('2', 'not available')], max_length=15)),
                ('packagenumber', models.IntegerField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapplication.agencys')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('booking_id', models.CharField(default='null', max_length=100)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapplication.packages')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfiles',
            fields=[
                ('AgencyName', models.CharField(blank=True, max_length=50)),
                ('Ownername', models.CharField(blank=True, max_length=50)),
                ('Mobilenumber', models.CharField(blank=True, max_length=50)),
                ('AddressLine1', models.CharField(blank=True, max_length=50)),
                ('AddressLine2', models.CharField(blank=True, max_length=50)),
                ('Postcode', models.CharField(blank=True, max_length=50)),
                ('State', models.CharField(blank=True, max_length=250)),
                ('Area', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('LicenceNumber', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('RegistrationDocument', models.ImageField(upload_to='')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
